language: python
python:
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "pypy3"  # currently Python 3.6.1,  PyPy 7.1.1-beta0
install:
  - pip install -r requirements.txt
  - python -m spacy download en_core_web_sm
  - python -m spacy download it_core_news_sm
  - pip install .
script: pytest
