language: python
os:
  - linux
  - osx
  - windows
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
install:
  - pip install -r requirements.txt
  - python -m spacy download en_core_web_sm
  - python -m spacy download it_core_news_sm
  - pip install .
script: pytest
